services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vocabPractice
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - .:/workspace
    working_dir: /workspace/backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "5174:5174"
    depends_on:
      - db
      - ollama
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    volumes:
      - ollama_data:/root/.ollama
      - ollama-models:/root/.ollama/models
      - ./ollama:/app
    working_dir: /app
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  postgres_data:
  ollama_data:
  ollama-models:
